In [2]:
# antes de empezar importamos la librería de NumPy para poder trabajar con todos sus métodos. 
import numpy as np

# Pair Numpy
## Creación y Indexación:
Crea un array 1D con 50 valores aleatorio del 10 al 99. Accede a los elementos en las posiciones múltiplos de 5.

Crea un array 1D con 30 valores del 1 al 20 (ambos incluidos). Utiliza indexación para obtener los elementos en las posiciones impares.

Crea un array 2D de forma (4, 6) con números aleatorios decimales (no deben estar comprendidos solo entre 0 y 1). Accede a la última fila de la matriz. Los decimales deben estar redondeados a 2 decimales.

In [16]:
array1= np.random.randint(10,99,50)
print(array1)

[93 47 29 80 12 73 64 79 32 96 68 43 16 74 68 79 56 76 94 80 31 11 46 46
 37 88 33 71 51 85 83 89 26 79 78 92 46 52 14 97 76 47 60 68 32 75 26 19
 27 50]


In [17]:
array1[::5]


array([93, 73, 68, 79, 31, 88, 83, 92, 76, 75])

In [19]:
# Ejercicio 2
array1= np.random.randint(1,20,30)
print(array1)

[ 2 10 10  2 14 12  3 19  9 13 17  5  1 18  5 14 12 17 16 19  8  7 13 15
 18 13  5  8 12 12]


In [20]:
array1[0::2]

array([ 2, 10, 14,  3,  9, 17,  1,  5, 12, 16,  8, 13, 18,  5, 12])

In [31]:
# Ejercicio 3
#Crea un array 2D de forma (4, 6) con números aleatorios decimales (no deben estar comprendidos solo entre 0 y 1). 
# Accede a la última fila de la matriz. Los decimales deben estar redondeados a 2 decimales.

array3 = np.random.random_sample((4, 6)) * 100 
array3

array([[81.38648701,  3.68512343,  9.59114579, 33.16899072,  4.60297117,
         9.44851008],
       [16.91932144, 35.22155891,  0.29584819, 77.27270854, 97.83577469,
        74.62311285],
       [70.58520973, 26.45555493, 42.85206684, 33.54443846, 80.52129824,
        62.82492808],
       [22.67738943, 51.27468046, 31.91494969, 92.98317555, 26.80599522,
        71.45914614]])

In [33]:
decimales= np.round(array3,2)
print(decimales[3])

[22.68 51.27 31.91 92.98 26.81 71.46]


# Reshape y Transpose:
## Ejercicios con reshape:
Crea un array 3D de forma (2, 3, 4) con valores aleatorios entre 1 y 100 (ambos inclusive). Utiliza reshape para convertirlo en un array 2D. Deberás pensar en la forma que es correcta para hacer este cambio.

Crea un array 3D de forma (3, 4, 5) con valores enteros del 1 al 61 (sin incluir). Utiliza reshape para convertirlo en un array 2D.

## Ejercicios con transpose:
Utiliza el array 3D del ejercicio 2 de reshape. Utiliza transpose para permutar los ejes y obtener un nuevo array con forma (5, 4, 3).

Utiliza el array 3D del ejercicio 2 de reshape. Utiliza transpose para cambiar el orden de los ejes y obtener un nuevo array con forma (3, 5, 4).

# Funciones Aritméticas y Estadísticas:

Crea un array de tres 3D con elementos entre el 0 y 1 de forma (2, 3, 5) cuyos valores solo tengan 1 decimal.

Crea un array vacío con la misma forma y dimensiones que el array creado anteriormente. Vamos a reemplazar los valores de la matriz vacía que nos acabamos de crear pero basándonos en los valores del primer array bajo las siguientes condiciones:

- Si el valor del array es igual que la media, se reemplaza por "A".

- Si el valor del array es mayor que la media, se reemplaza por "B".

- Si el valor del array es menor que la media, se reemplaza por "C".

- Si el valor es igual que el máximo, se reemplaza por "D".

- Si el valor es igual que el mínimo, se reemplaza por "E".

In [3]:
array5 = np.random.rand(2,3,5)
array5

array([[[0.84293984, 0.83249746, 0.57352934, 0.15083232, 0.71820583],
        [0.97925695, 0.19734243, 0.20751398, 0.30485163, 0.53950355],
        [0.16965144, 0.72475628, 0.40023523, 0.18260913, 0.24417182]],

       [[0.08015758, 0.98087929, 0.55926931, 0.6044252 , 0.15225115],
        [0.21898432, 0.65298089, 0.30282266, 0.31605266, 0.44239334],
        [0.64532708, 0.42734654, 0.21395637, 0.40833593, 0.11361228]]])

In [4]:
decimales1= np.round(array5,1)
decimales1

array([[[0.8, 0.8, 0.6, 0.2, 0.7],
        [1. , 0.2, 0.2, 0.3, 0.5],
        [0.2, 0.7, 0.4, 0.2, 0.2]],

       [[0.1, 1. , 0.6, 0.6, 0.2],
        [0.2, 0.7, 0.3, 0.3, 0.4],
        [0.6, 0.4, 0.2, 0.4, 0.1]]])

In [6]:
np.mean(decimales1)

0.43666666666666665

In [5]:
vacio = np.empty((2,3,5))
vacio

array([[[0.8, 0.8, 0.6, 0.2, 0.7],
        [1. , 0.2, 0.2, 0.3, 0.5],
        [0.2, 0.7, 0.4, 0.2, 0.2]],

       [[0.1, 1. , 0.6, 0.6, 0.2],
        [0.2, 0.7, 0.3, 0.3, 0.4],
        [0.6, 0.4, 0.2, 0.4, 0.1]]])

In [10]:
max =np.max(vacio)

1.0

In [12]:
min=np.min(vacio)

In [13]:
result = np.where(vacio == 0.4366, "A", np.where(vacio == max, "D", np.where(vacio == min, "E", np.where(vacio > 0.4366, "B", "C"))))
result

array([[['B', 'B', 'B', 'C', 'B'],
        ['B', 'C', 'C', 'C', 'B'],
        ['C', 'B', 'C', 'C', 'C']],

       [['E', 'B', 'B', 'B', 'C'],
        ['C', 'B', 'C', 'C', 'C'],
        ['B', 'C', 'C', 'C', 'E']]], dtype='<U1')